---
- name: configure web VM with elk
  hosts: elk
  remote_user: azureuser
  become: true
  tasks:

    - name: set vm.max_map_count to 26144
      sysctl: 
        name=vm.max_map_count 
        value=262144 
      
    - name: install docker.io
      apt: 
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    - name: install python3
      apt: 
        name: python3-pip 
        state: present
      
    - name: install docker (python)
      pip: 
        name: docker
        state: present

    - name: Install Elk Container (761)
      docker_container: 
        name: elk
        image: sebp/elk:761
        state: started 
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044
        
    - name: enable service docker on boot
      systemd: 
        name: docker
        enabled: yes