---
- name: Metricbeat Installation Play
  hosts: webservers
  become: true
  tasks:

    - name: Downloading Metricbeat(DEB)
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
        dest: ./
      
    - name: Installing Metricbeat(INST)
      apt:
        deb: ./metricbeat-7.4.0-amd64.deb
      
    - name: Copying Metricbeat Configurations From Container
      ansible.builtin.copy: 
        src: /etc/ansible/metricbeat-config.yml 
        dest: /etc/metricbeat/metricbeat.yml
      
    - name: Running enabling metricbeat modules
      command: metricbeat modules enable docker
      
    - name: Running metricbeat setup 
      command: metricbeat setup
      
    - name: Running service metricbeat start
      command: service metricbeat start
      
    - name: Enable metricbeat on service boot
      systemd: 
        name: metricbeat
        enabled: yes